### ISSUE TITLE
Entities de we publiceren naar manage productie moeten op prodaccepted staan

### ISSUE THREAD

**Issue by phavekes** [SURFnet/sp-dashboard#904]
[This issue is imported from pivotal - Originaly created at Feb 15, 2019 by Bart Geesink](https://www.pivotaltracker.com/story/show/164005623)

Op dit moment worden productie entities met "testaccepted" status gepubliceerd. Dat moet "prodaccepted" worden. Bij voorkeur kan dit worden geconfigureerd.

**Comment by phavekes** [comment]
@bartgeesink Typo in de description?

Ik gok dat het moet zijn:

Op dit moment worden productie entities met "testaccepted" status gepubliceerd. Dat moet "~~testaccepted~~prodaccepted" worden. Bij voorkeur kan dit worden geconfigureerd.  (Michiel Kodde - Feb 18, 2019)

**Comment by phavekes** [comment]
Do you suggest we add a configuration section that allows us to set the different publication stati?

```
manage_status:
    test:
        new: testaccepted
        edit: testaccepted
    production:
        new: notprodaccepted
        edit: prodaccepted
```
 (Michiel Kodde - Feb 18, 2019)
